#+BEGIN_COMMENT
.. title: 《学习之道》读书笔记
.. slug: xue-xi-zhi-dao-du-shu-bi-ji
.. date: 2019-03-29 14:22:32 UTC+08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

这本书是coursera知名课程《learn how to learn》老师所写的。说起来，好多MOOC的老师之后都会出一本课程讲义书，比如国内的肖星出的财务报表一书。

* 发散模式和专注模式
作者论述了两种模式，并且告诉我们要善于转换这两种模式。以爱迪生为例，他惊人的创造力来源于一个生活习惯：在碰到困难的时候先去小睡一会儿，激活发散模式。
其实这个道理我们大多数都知道， 初高中老师就教授过一个理论，那就是如果求解一个问题，十五分钟后还没想到解法的话，就先不管他，出去溜溜再回来解决。思路基本一致。

** 激活发散模式的方法
- 去健身房
- 运动，打球
- 洗澡
- 弹奏乐器
- 冥想
- 睡觉（最有效）

** 反直觉的无效方式
- 打游戏
- 上网
- 聊天
- 处理小事务
- 阅读休闲事务
- 看电视，电影
-

可以认为，你先用专注模式将待分散模式处理的事情填充你的心理buffer，然后去放飞自我，这时候可能潜意识中就会处理这些事务。而如果你还是动脑的话，就得不到发散模式的帮助了。

而睡觉是最彻底的切换两种模式的途径，睡觉的时候，会把专注模式彻底关闭，然后发散模式会开始处理之前存入的事情。 睡一觉就想到解决问题的方法并不是空虚来风。

在这里我对自己进行下反思。因为我长期不愿意让大脑放松下来，在车上也习惯于看书。在路上走路也倾向于玩手机，看新闻。这么做，是不是就丧失了很多切换到发散模式的机会，导致于我的创造力低下呢？

* 工作记忆和长期记忆
就是短暂记忆要演变为长期记忆，最好的方式是隔几天回顾一次，类似艾兵豪斯记忆曲线。对新概念的第一次回顾，要定在同一天内。要善用记忆卡。

而且我们的长期记忆实际上也是有半衰期的，也是要时常回顾，才能不彻底遗忘。

* 组件构建和避免能力错觉
组件构建的方法（我个人感觉更像是学习知识的方法）

* 学习卡                                                           :noexport:
:PROPERTIES:
:ANKI_DECK: 学习之道
:END:

** 测试
:PROPERTIES:
:ANKI_NOTE_TYPE: 基础
:ANKI_NOTE_ID: 1553850025328
:END:
*** 正面
hhh
*** 背面
呵呵

** Item
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_NOTE_ID: 1553850577173
:END:
*** Front
测试
*** Back
哈哈哈
